### PR TITLE
Adding place_find_from_text

### PR DESCRIPTION
**Pull request by leepage87**
Adds a function to call the `place/findplacefromtext` endpoint of the Places API.

### CODE REVIEW

**Comment by sntran** [comment]
Thanks for the new functionality! Since my gitpod workspace is broken, I can't review it from here. I'll check this later in my home computer.

**Comment by sntran** [comment]
Hi @leepage87, I have checked out your changes and they look good.

There are some extra white spaces. Would you mind cleaning them out before I merge?

**Comment by leepage87** [comment]
> There are some extra white spaces. Would you mind cleaning them out before I merge?

Done!

**Comment by sntran** [comment]
Awesome! Thanks. I'll update the README later.

**Pull request merged**
